### ISSUE TITLE
Error message when doing `<leader>x<` inside Git conflict

### ISSUE THREAD

**Issue by mawkler** [inkarkat/vim-ConflictMotions#1]
Hi! I'm getting an error message when I do `<leader>x<` inside a Git conflict.

To reproduce, do `<leader>x<` with the cursor somewhere between `HEAD` and `=======` in the following example:

```cs
Finance team
-Charles
-Lisa
-John
<<<<<<< HEAD
-Stacy
-Alexander

Marketing team
- Collins
- Linda
- Patricia
- Morgan
- Amanda
=======
>>>>>>> master
```

The following is the error message:

```vim
Error detected while processing function ConflictMotions#Take[66]..ConflictMot
ions#TakeFromConflict[64]..<SNR>36_CaptureSection[10]..ingo#register#KeepRegis
terExecuteOrFunc[24]..ingo#actions#ExecuteOrFunc[4]..CountJump#OMapping:
line    1:
E117: Unknown function: ingo#register#pending#ExecuteOrFunc
E15: Invalid expression: ingo#register#pending#ExecuteOrFunc(function('CountJu
mp#Mapping'), a:Function, a:arguments)
Error detected while processing function ConflictMotions#Take[66]..ConflictMot
ions#TakeFromConflict:
line   64:
E171: Missing :endif
Error detected while processing function ConflictMotions#Take:
line   66:
E171: Missing :endif
```

This is my minimal `.vimrc`:

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'ingo-library'
Plugin 'ConflictMotions'
Plugin 'inkarkat/vim-CountJump'
call vundle#end()
```

**Comment by inkarkat** [comment]
Hi! Looks like your version of the _ingo-library_ is too old for the CountJump plugin; the latest version 1.91 requires ingo-library 1.041 or higher.

If I understand your `Plug` definitions correctly, you're automatically consuming CountJump directly from GitHub, but not the other two libraries; these are now available on GitHub as well: https://github.com/inkarkat/vim-ingo-library and https://github.com/inkarkat/vim-ConflictMotions. If you switch those over to GitHub (and consistently use either the _master_ or _stable_ branch for those repos), you don't need to worry about these update problems any longer!

**Comment by mawkler** [comment]
Thanks, that solved it! I had a feeling it had something to do with the versions, and that explains why simply running `:PluginUpdate` didn't solve it!
